'use client'

import { useState, useRef } from 'react'
import {
  QrCode, Download, Printer, Copy, MapPin, Lightbulb, Check
} from 'lucide-react'
import { QRCodeCanvas } from 'qrcode.react'
import type { DashboardData } from '@/lib/types'

export default function QRCodeGenerator({ data }: { data: DashboardData | null }) {
  const [copied, setCopied] = useState(false)
  const [qrSize, setQrSize] = useState(280)
  const qrContainerRef = useRef<HTMLDivElement>(null)

  const surveyUrl = typeof window !== 'undefined'
    ? `${window.location.origin}/survey/consent`
    : 'https://dpems.rsjafarmedika.com/survey/consent'

  const handleDownload = () => {
    const canvas = qrContainerRef.current?.querySelector('canvas')
    if (!canvas) return
    const link = document.createElement('a')
    link.download = 'QR-Akupuntur-Herbal-RSU-Jafar-Medika.png'
    link.href = canvas.toDataURL('image/png')
    link.click()
  }

  const handlePrint = () => {
    const canvas = qrContainerRef.current?.querySelector('canvas')
    if (!canvas) return
    const imgSrc = canvas.toDataURL('image/png')
    const dateStr = new Date().toLocaleDateString('id-ID')
    const win = window.open('', '_blank')
    if (!win) return
    const html = '<html><head><title>QR Code - Poli Akupuntur & Herbal</title>'
      + '<style>'
      + 'body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:system-ui,sans-serif;margin:0;padding:40px}'
      + 'img{width:400px;height:400px;border:2px solid #0D9488;border-radius:16px;padding:16px}'
      + 'h1{font-size:18px;color:#1e293b;margin:16px 0 4px}'
      + 'h2{font-size:14px;color:#475569;margin:2px 0;font-weight:400}'
      + 'p{font-size:13px;color:#64748b;margin:2px 0}'
      + '.footer{margin-top:24px;font-size:11px;color:#94a3b8}'
      + '.placement{margin-top:20px;padding:16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;text-align:left;max-width:500px}'
      + '.placement h3{font-size:13px;color:#1e293b;margin:0 0 8px}'
      + '.placement ul{margin:0;padding-left:20px;color:#64748b;font-size:12px}'
      + '.placement li{margin-bottom:4px}'
      + '</style></head>'
      + '<body>'
      + '<h1>Poli Akupuntur & Herbal</h1>'
      + "<h2>RSU Ja'far Medika Karanganyar</h2>"
      + '<img src="' + imgSrc + '" />'
      + '<p>Scan QR code untuk mengisi survei pengalaman pasien</p>'
      + '<p class="footer">Generated by DPEMS &mdash; ' + dateStr + '</p>'
      + '<div class="placement">'
      + '<h3>Panduan Penempatan</h3>'
      + '<ul>'
      + '<li>Ruang tunggu poli — tempel di dinding dekat kursi tunggu utama</li>'
      + '<li>Meja resepsionis — letakkan di meja depan agar staf bisa menunjukkan ke pasien</li>'
      + '<li>Area terapi / ruang akupuntur — pasang di dekat pintu masuk ruang terapi</li>'
      + '<li>Kartu nama / brosur pasien — sertakan di materi edukasi pasien baru</li>'
      + '</ul>'
      + '</div>'
      + '<scr' + 'ipt>window.onload=function(){window.print();};</scr' + 'ipt>'
      + '</body></html>'
    win.document.write(html)
    win.document.close()
  }

  const handleCopyUrl = async () => {
    try {
      await navigator.clipboard.writeText(surveyUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      const textArea = document.createElement('textarea')
      textArea.value = surveyUrl
      document.body.appendChild(textArea)
      textArea.select()
      document.execCommand('copy')
      document.body.removeChild(textArea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const placementGuides = [
    { location: 'Ruang tunggu poli', desc: 'Tempel di dinding dekat kursi tunggu utama', emoji: '🚪' },
    { location: 'Meja resepsionis', desc: 'Letakkan di meja depan agar staf bisa menunjukkan ke pasien', emoji: '📝' },
    { location: 'Area terapi / ruang akupuntur', desc: 'Pasang di dekat pintu masuk ruang terapi', emoji: '🪑' },
    { location: 'Kartu nama / brosur pasien', desc: 'Sertakan di materi edukasi pasien baru', emoji: '👨‍⚕️' },
  ]

  const usageTips = [
    { title: 'Ukuran Cetak', desc: 'Minimal 10x10 cm agar mudah discan dari jarak 1 meter' },
    { title: 'Laminasi', desc: 'Gunakan kertas glossy atau laminasi agar tahan lama' },
    { title: 'Pencahayaan', desc: 'Pastikan area penempatan QR Code memiliki cahaya cukup' },
    { title: 'Label', desc: 'Beri label "Scan untuk isi survei" di bawah QR Code' },
    { title: 'Maintenance', desc: 'Ganti QR Code setiap 6 bulan atau jika URL berubah' },
  ]

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-lg bg-teal-600 flex items-center justify-center shrink-0 shadow-sm">
            <QrCode className="w-5 h-5 text-white" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-bold text-slate-800 font-[family-name:var(--font-display)]">
                QR Code Survei Pasien
              </h3>
              <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200/60">
                Auto-Generate
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1 leading-relaxed">
              Generate dan cetak QR Code untuk disimpan di ruang tunggu Poli Akupuntur &amp; Herbal. Pasien cukup scan QR code untuk langsung mengisi survei pengalaman mereka.
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* QR Code Card */}
        <div className="bg-white rounded-xl border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-5">
            <div>
              <h4 className="text-sm font-bold text-slate-800 font-[family-name:var(--font-display)]">Poli Akupuntur &amp; Herbal</h4>
              <p className="text-[11px] text-slate-400 mt-0.5">Layanan integratif stroke &amp; nyeri</p>
            </div>
            <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200/60">
              Aktif
            </span>
          </div>

          {/* QR Code */}
          <div className="flex flex-col items-center">
            <div
              ref={qrContainerRef}
              className="p-4 bg-white rounded-2xl border-2 border-dashed border-teal-200 shadow-sm"
            >
              <QRCodeCanvas
                value={surveyUrl || 'https://dpems.rsjafarmedika.com/survey/consent'}
                size={qrSize}
                bgColor="#ffffff"
                fgColor="#0f172a"
                level="H"
                includeMargin={false}
              />
            </div>

            {/* URL Preview */}
            <div className="mt-4 w-full bg-slate-50 rounded-lg p-3 flex items-center gap-2">
              <div className="flex-1 min-w-0">
                <p className="text-[10px] text-slate-400 font-medium mb-0.5">URL Survei</p>
                <p className="text-xs text-slate-600 truncate font-mono">
                  {surveyUrl || 'https://dpems.rsjafarmedika.com/survey/consent'}
                </p>
              </div>
              <button
                onClick={handleCopyUrl}
                className="p-2 rounded-lg text-slate-400 hover:text-teal-600 hover:bg-teal-50 transition-colors shrink-0"
                title="Salin URL"
              >
                {copied ? <Check className="w-4 h-4 text-teal-600" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* Size Selector */}
          <div className="mt-4 flex items-center gap-3">
            <span className="text-[11px] text-slate-500 font-medium">Ukuran:</span>
            <div className="flex gap-1.5">
              {[
                { label: 'S', size: 200 },
                { label: 'M', size: 280 },
                { label: 'L', size: 380 },
              ].map((opt) => (
                <button
                  key={opt.label}
                  onClick={() => setQrSize(opt.size)}
                  className={`w-8 h-8 rounded-lg text-xs font-bold transition-colors ${
                    qrSize === opt.size
                      ? 'bg-teal-600 text-white shadow-sm'
                      : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Actions + Placement + Tips + Stats */}
        <div className="space-y-6">
          {/* Action Buttons */}
          <div className="bg-white rounded-xl border border-slate-200 p-5 space-y-3">
            <h4 className="text-sm font-bold text-slate-800 font-[family-name:var(--font-display)] mb-4">Aksi</h4>
            <button
              onClick={handleDownload}
              className="w-full flex items-center gap-3 p-3.5 rounded-xl bg-gradient-to-r from-teal-600 to-teal-500 text-white hover:from-teal-700 hover:to-teal-600 transition-all shadow-lg shadow-teal-500/20 hover:shadow-teal-500/30"
            >
              <div className="w-9 h-9 rounded-lg bg-white/20 flex items-center justify-center shrink-0">
                <Download className="w-4 h-4" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold">Download PNG</p>
                <p className="text-[10px] text-teal-100">Simpan file gambar QR Code</p>
              </div>
            </button>
            <button
              onClick={handlePrint}
              className="w-full flex items-center gap-3 p-3.5 rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 hover:border-slate-300 transition-all"
            >
              <div className="w-9 h-9 rounded-lg bg-slate-100 flex items-center justify-center shrink-0">
                <Printer className="w-4 h-4 text-slate-600" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-slate-700">Cetak / Print</p>
                <p className="text-[10px] text-slate-400">Buka dialog cetak langsung</p>
              </div>
            </button>
            <button
              onClick={handleCopyUrl}
              className="w-full flex items-center gap-3 p-3.5 rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 hover:border-slate-300 transition-all"
            >
              <div className="w-9 h-9 rounded-lg bg-slate-100 flex items-center justify-center shrink-0">
                {copied ? <Check className="w-4 h-4 text-teal-600" /> : <Copy className="w-4 h-4 text-slate-600" />}
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-slate-700">{copied ? 'URL Tersalin!' : 'Salin URL Survei'}</p>
                <p className="text-[10px] text-slate-400">{surveyUrl || 'https://dpems.rsjafarmedika.com/survey/consent'}</p>
              </div>
            </button>
          </div>

          {/* Placement Guide */}
          <div className="bg-white rounded-xl border border-slate-200 p-5">
            <h4 className="text-sm font-bold text-slate-800 font-[family-name:var(--font-display)] mb-3 flex items-center gap-2">
              <MapPin className="w-4 h-4 text-teal-600" />
              Panduan Penempatan
            </h4>
            <div className="space-y-2.5">
              {placementGuides.map((item) => (
                <div key={item.emoji} className="flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-teal-50 border border-teal-200/60 flex items-center justify-center text-sm shrink-0 mt-0.5">
                    {item.emoji}
                  </span>
                  <div>
                    <p className="text-xs font-semibold text-slate-700">{item.location}</p>
                    <p className="text-[11px] text-slate-400">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Usage Tips */}
          <div className="bg-gradient-to-br from-amber-50 to-amber-100/60 rounded-xl border border-amber-200 p-4">
            <p className="text-xs font-semibold text-amber-800 mb-2 flex items-center gap-1.5">
              <Lightbulb className="w-3.5 h-3.5" />
              Tips Pemakaian
            </p>
            <ul className="space-y-1.5 text-[11px] text-amber-700 leading-relaxed">
              {usageTips.map((tip) => (
                <li key={tip.title} className="flex gap-2">
                  <span className="text-amber-500 shrink-0">&#8226;</span>
                  <span><span className="font-medium">{tip.title}:</span> {tip.desc}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Quick Stats Card */}
          <div className="bg-gradient-to-br from-teal-50 to-teal-100/60 rounded-xl border border-teal-200 p-4">
            <p className="text-xs font-semibold text-teal-800 mb-3">Quick Stats</p>
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-white/70 rounded-lg p-3 text-center">
                <p className="text-lg font-bold text-teal-700 font-[family-name:var(--font-display)]">{data?.totalSurveys ?? 0}</p>
                <p className="text-[10px] text-teal-600">Total Survei</p>
              </div>
              <div className="bg-white/70 rounded-lg p-3 text-center">
                <p className="text-lg font-bold text-teal-700 font-[family-name:var(--font-display)]">{data?.responseRate ?? 0}%</p>
                <p className="text-[10px] text-teal-600">Response Rate</p>
              </div>
              <div className="bg-white/70 rounded-lg p-3 text-center">
                <p className="text-lg font-bold text-amber-600 font-[family-name:var(--font-display)]">{data?.avgPainReduction ?? 0}%</p>
                <p className="text-[10px] text-teal-600">Pain Reduction</p>
              </div>
              <div className="bg-white/70 rounded-lg p-3 text-center">
                <p className="text-lg font-bold text-emerald-600 font-[family-name:var(--font-display)]">{data?.nps?.score > 0 ? `+${data.nps.score}` : data?.nps?.score ?? '-'}</p>
                <p className="text-[10px] text-teal-600">NPS Score</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
